version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - '${DB_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: 'address'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'address'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U address"]

volumes:
  postgres:
    driver: local
